from datetime import datetime, timezone
from typing import Optional

from sqlmodel import Field, SQLModel


class Simulation(SQLModel, table=True):
    __tablename__ = "simulations"

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    site_id: int = Field(foreign_key="sites.id", index=True)
    critical_active_power_w: float = Field(default=0, ge=0)
    backup_time_hours: float = Field(default=1.5, gt=0)
    power_factor: float = Field(default=0.8, gt=0, le=1)
    air_conditioner_power_w: float = Field(default=0, ge=0)
    air_conditioner_is_critical: bool = Field(default=False)
    other_critical_power_w: float = Field(default=0, ge=0)
    other_non_critical_power_w: float = Field(default=0, ge=0)
    panel_power_watts: float = Field(default=550, gt=0)
    panel_type: str = Field(default="Monocristallin", max_length=80)
    panel_length_m: float = Field(default=2.28, gt=0)
    panel_width_m: float = Field(default=1.13, gt=0)
    panel_area_m2: float = Field(default=2.58, gt=0)
    panel_spacing_factor: float = Field(default=1.2, ge=1)
    installed_panel_count: int = Field(default=0, ge=0)
    battery_capacity_ah: float = Field(default=200, gt=0)
    battery_voltage: float = Field(default=12, gt=0)
    battery_type: str = Field(default="LiFePO4", max_length=80)
    battery_energy_kwh: float = Field(default=2.4, gt=0)
    installed_battery_count: int = Field(default=0, ge=0)
    installed_inverter_power_watts: float = Field(default=0, ge=0)
    installed_controller_count: int = Field(default=0, ge=0)
    installed_controller_current_a: float = Field(default=0, ge=0)
    installed_dc_spd_count: int = Field(default=0, ge=0)
    installed_ac_spd_count: int = Field(default=0, ge=0)
    installed_earthing_kit_count: int = Field(default=0, ge=0)
    battery_dod: float = Field(default=0.8, gt=0, le=1)
    battery_efficiency: float = Field(default=0.95, gt=0, le=1)
    controller_efficiency: float = Field(default=0.96, gt=0, le=1)
    inverter_efficiency: float = Field(default=0.93, gt=0, le=1)
    cable_loss_factor: float = Field(default=0.03, ge=0, le=1)
    dc_cable_length_m: float = Field(default=20, ge=0)
    ac_cable_length_m: float = Field(default=30, ge=0)
    dc_voltage_drop_limit_percent: float = Field(default=3, gt=0, le=10)
    ac_voltage_drop_limit_percent: float = Field(default=5, gt=0, le=10)
    temperature_loss_factor: float = Field(default=0.05, ge=0, le=1)
    dust_loss_factor: float = Field(default=0.03, ge=0, le=1)
    safety_factor: float = Field(default=1.25, ge=1)
    lightning_protection_required: bool = Field(default=True)
    dc_spd_required: bool = Field(default=True)
    ac_spd_required: bool = Field(default=True)
    earthing_required: bool = Field(default=True)
    earthing_resistance_target_ohm: float = Field(default=5, gt=0)
    earthing_resistance_measured_ohm: float = Field(default=0, ge=0)
    panel_unit_price: float = Field(default=150, ge=0)
    battery_unit_price: float = Field(default=250, ge=0)
    inverter_price: float = Field(default=500, ge=0)
    controller_price: float = Field(default=300, ge=0)
    air_conditioner_price: float = Field(default=0, ge=0)
    accessories_price: float = Field(default=400, ge=0)
    protection_price: float = Field(default=250, ge=0)
    installation_price: float = Field(default=500, ge=0)
    labor_price: float = Field(default=500, ge=0)
    maintenance_price: float = Field(default=0, ge=0)
    snel_operating_cost: float = Field(default=0, ge=0)
    generator_operating_cost: float = Field(default=0, ge=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
