begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  full_name varchar(120) not null,
  email varchar(255) not null unique,
  hashed_password text not null,
  role varchar(20) not null default 'student',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint users_role_check check (role in ('admin', 'student'))
);

create index if not exists ix_users_email on public.users (email);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(150) not null,
  organization varchar(150) not null default '',
  phone varchar(40) not null default '',
  email varchar(255) not null default '',
  address text not null default '',
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_clients_user_id on public.clients (user_id);

create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(150) not null,
  city varchar(80) not null,
  country varchar(80) not null,
  site_type varchar(100) not null,
  description text not null default '',
  latitude double precision not null default 0,
  longitude double precision not null default 0,
  operating_hours_per_day double precision not null default 24,
  autonomy_days double precision not null default 2,
  target_backup_hours double precision not null default 24,
  solar_irradiation_hours double precision not null default 5,
  system_efficiency double precision not null default 0.8,
  system_voltage integer not null default 48,
  available_area_m2 double precision not null default 0,
  usable_area_ratio double precision not null default 1,
  layout_length_m double precision not null default 0,
  layout_width_m double precision not null default 0,
  generator_available boolean not null default true,
  generator_failure_scenario boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint sites_operating_hours_check check (operating_hours_per_day >= 0 and operating_hours_per_day <= 24),
  constraint sites_autonomy_days_check check (autonomy_days > 0),
  constraint sites_target_backup_hours_check check (target_backup_hours > 0),
  constraint sites_solar_hours_check check (solar_irradiation_hours > 0),
  constraint sites_efficiency_check check (system_efficiency > 0 and system_efficiency <= 1),
  constraint sites_available_area_check check (available_area_m2 >= 0),
  constraint sites_usable_area_ratio_check check (usable_area_ratio > 0 and usable_area_ratio <= 1)
);

create index if not exists ix_sites_user_id on public.sites (user_id);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites(id) on delete cascade,
  name varchar(120) not null,
  category varchar(80) not null,
  power_watts double precision not null,
  quantity integer not null default 1,
  hours_per_day double precision not null default 24,
  is_critical boolean not null default true,
  notes text not null default '',
  position_x_m double precision not null default 0,
  position_y_m double precision not null default 0,
  footprint_length_m double precision not null default 0,
  footprint_width_m double precision not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint equipment_power_check check (power_watts > 0),
  constraint equipment_quantity_check check (quantity >= 1),
  constraint equipment_hours_check check (hours_per_day >= 0 and hours_per_day <= 24)
);

create index if not exists ix_equipment_site_id on public.equipment (site_id);

create table if not exists public.simulations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  site_id bigint not null references public.sites(id) on delete cascade,
  panel_power_watts double precision not null default 550,
  panel_type varchar(80) not null default 'Monocristallin',
  panel_length_m double precision not null default 2.28,
  panel_width_m double precision not null default 1.13,
  panel_area_m2 double precision not null default 2.58,
  panel_spacing_factor double precision not null default 1.2,
  battery_capacity_ah double precision not null default 200,
  battery_voltage double precision not null default 12,
  battery_type varchar(80) not null default 'LiFePO4',
  battery_energy_kwh double precision not null default 2.4,
  battery_dod double precision not null default 0.8,
  controller_efficiency double precision not null default 0.96,
  inverter_efficiency double precision not null default 0.93,
  cable_loss_factor double precision not null default 0.03,
  temperature_loss_factor double precision not null default 0.05,
  dust_loss_factor double precision not null default 0.03,
  safety_factor double precision not null default 1.25,
  panel_unit_price double precision not null default 150,
  battery_unit_price double precision not null default 250,
  inverter_price double precision not null default 500,
  controller_price double precision not null default 300,
  accessories_price double precision not null default 400,
  labor_price double precision not null default 500,
  maintenance_price double precision not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  constraint simulations_panel_power_check check (panel_power_watts > 0),
  constraint simulations_panel_length_check check (panel_length_m > 0),
  constraint simulations_panel_width_check check (panel_width_m > 0),
  constraint simulations_panel_area_check check (panel_area_m2 > 0),
  constraint simulations_panel_spacing_check check (panel_spacing_factor >= 1),
  constraint simulations_battery_capacity_check check (battery_capacity_ah > 0),
  constraint simulations_battery_voltage_check check (battery_voltage > 0),
  constraint simulations_battery_energy_check check (battery_energy_kwh > 0),
  constraint simulations_battery_dod_check check (battery_dod > 0 and battery_dod <= 1),
  constraint simulations_controller_efficiency_check check (controller_efficiency > 0 and controller_efficiency <= 1),
  constraint simulations_inverter_efficiency_check check (inverter_efficiency > 0 and inverter_efficiency <= 1),
  constraint simulations_cable_loss_check check (cable_loss_factor >= 0 and cable_loss_factor <= 1),
  constraint simulations_temperature_loss_check check (temperature_loss_factor >= 0 and temperature_loss_factor <= 1),
  constraint simulations_dust_loss_check check (dust_loss_factor >= 0 and dust_loss_factor <= 1),
  constraint simulations_safety_factor_check check (safety_factor >= 1),
  constraint simulations_panel_unit_price_check check (panel_unit_price >= 0),
  constraint simulations_battery_unit_price_check check (battery_unit_price >= 0),
  constraint simulations_inverter_price_check check (inverter_price >= 0),
  constraint simulations_controller_price_check check (controller_price >= 0),
  constraint simulations_accessories_price_check check (accessories_price >= 0),
  constraint simulations_labor_price_check check (labor_price >= 0),
  constraint simulations_maintenance_price_check check (maintenance_price >= 0)
);

create index if not exists ix_simulations_user_id on public.simulations (user_id);
create index if not exists ix_simulations_site_id on public.simulations (site_id);

create table if not exists public.simulation_results (
  id bigint generated by default as identity primary key,
  simulation_id bigint not null unique references public.simulations(id) on delete cascade,
  total_power_watts double precision not null,
  critical_power_watts double precision not null default 0,
  non_critical_power_watts double precision not null default 0,
  daily_energy_wh double precision not null,
  critical_energy_wh double precision not null default 0,
  non_critical_energy_wh double precision not null default 0,
  corrected_energy_wh double precision not null,
  required_pv_power_wc double precision not null,
  number_of_panels integer not null,
  panel_surface_required_m2 double precision not null default 0,
  panel_surface_with_spacing_m2 double precision not null default 0,
  available_surface_m2 double precision not null default 0,
  surface_status varchar(80) not null default '',
  required_battery_capacity_wh double precision not null,
  required_battery_capacity_ah double precision not null,
  number_of_batteries integer not null,
  backup_time_hours double precision not null default 0,
  controller_current_a double precision not null,
  inverter_power_watts double precision not null,
  feasibility_status varchar(80) not null default '',
  dimensioning_state text not null default '',
  load_shedding_required boolean not null default false,
  load_shedding_message text not null default '',
  warnings_json text not null default '[]',
  recommended_configuration_json text not null default '{}',
  total_cost double precision not null,
  recommendations text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  constraint simulation_results_number_of_panels_check check (number_of_panels >= 0),
  constraint simulation_results_number_of_batteries_check check (number_of_batteries >= 0),
  constraint simulation_results_total_cost_check check (total_cost >= 0)
);

create index if not exists ix_simulation_results_simulation_id on public.simulation_results (simulation_id);

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_clients_updated_at on public.clients;
create trigger trg_clients_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

drop trigger if exists trg_sites_updated_at on public.sites;
create trigger trg_sites_updated_at
before update on public.sites
for each row execute function public.set_updated_at();

drop trigger if exists trg_equipment_updated_at on public.equipment;
create trigger trg_equipment_updated_at
before update on public.equipment
for each row execute function public.set_updated_at();

commit;
