alter table if exists public.sites
  add column if not exists total_area_m2 double precision not null default 0,
  add column if not exists tower_area_m2 double precision not null default 0,
  add column if not exists rack_area_m2 double precision not null default 0,
  add column if not exists generator_area_m2 double precision not null default 0,
  add column if not exists other_blocked_area_m2 double precision not null default 0,
  add column if not exists snel_available boolean not null default true;

alter table if exists public.simulations
  add column if not exists critical_active_power_w double precision not null default 0,
  add column if not exists backup_time_hours double precision not null default 1.5,
  add column if not exists power_factor double precision not null default 0.8,
  add column if not exists air_conditioner_power_w double precision not null default 0,
  add column if not exists air_conditioner_is_critical boolean not null default false,
  add column if not exists other_critical_power_w double precision not null default 0,
  add column if not exists other_non_critical_power_w double precision not null default 0,
  add column if not exists installed_panel_count integer not null default 0,
  add column if not exists battery_efficiency double precision not null default 0.95,
  add column if not exists installed_battery_count integer not null default 0,
  add column if not exists installed_inverter_power_watts double precision not null default 0,
  add column if not exists installed_controller_count integer not null default 0,
  add column if not exists installed_controller_current_a double precision not null default 0,
  add column if not exists installed_dc_spd_count integer not null default 0,
  add column if not exists installed_ac_spd_count integer not null default 0,
  add column if not exists installed_earthing_kit_count integer not null default 0,
  add column if not exists air_conditioner_price double precision not null default 0,
  add column if not exists installation_price double precision not null default 500,
  add column if not exists snel_operating_cost double precision not null default 0,
  add column if not exists generator_operating_cost double precision not null default 0,
  add column if not exists dc_cable_length_m double precision not null default 20,
  add column if not exists ac_cable_length_m double precision not null default 30,
  add column if not exists dc_voltage_drop_limit_percent double precision not null default 3,
  add column if not exists ac_voltage_drop_limit_percent double precision not null default 5,
  add column if not exists lightning_protection_required boolean not null default true,
  add column if not exists dc_spd_required boolean not null default true,
  add column if not exists ac_spd_required boolean not null default true,
  add column if not exists earthing_required boolean not null default true,
  add column if not exists earthing_resistance_target_ohm double precision not null default 5,
  add column if not exists earthing_resistance_measured_ohm double precision not null default 0,
  add column if not exists protection_price double precision not null default 250;

alter table if exists public.simulation_results
  add column if not exists apparent_power_va double precision not null default 0,
  add column if not exists panel_unit_area_m2 double precision not null default 0,
  add column if not exists panel_total_area_m2 double precision not null default 0,
  add column if not exists panel_total_area_with_spacing_m2 double precision not null default 0,
  add column if not exists pv_cost double precision not null default 0,
  add column if not exists battery_cost double precision not null default 0,
  add column if not exists inverter_cost double precision not null default 0,
  add column if not exists controller_cost double precision not null default 0,
  add column if not exists air_conditioner_cost double precision not null default 0,
  add column if not exists protection_cost double precision not null default 0,
  add column if not exists installation_cost double precision not null default 0,
  add column if not exists accessories_cost double precision not null default 0,
  add column if not exists maintenance_cost double precision not null default 0,
  add column if not exists total_investment_cost double precision not null default 0,
  add column if not exists snel_operating_cost double precision not null default 0,
  add column if not exists generator_operating_cost double precision not null default 0,
  add column if not exists dc_cable_section_mm2 double precision not null default 0,
  add column if not exists ac_cable_section_mm2 double precision not null default 0,
  add column if not exists earth_cable_section_mm2 double precision not null default 0,
  add column if not exists dc_breaker_rating_a double precision not null default 0,
  add column if not exists ac_breaker_rating_a double precision not null default 0,
  add column if not exists dc_spd_required boolean not null default false,
  add column if not exists ac_spd_required boolean not null default false,
  add column if not exists lightning_protection_required boolean not null default false,
  add column if not exists earthing_required boolean not null default false,
  add column if not exists recommended_earthing_resistance_ohm double precision not null default 0,
  add column if not exists measured_earthing_resistance_ohm double precision not null default 0,
  add column if not exists grounding_status varchar(120) not null default '';
